---
- name: Fixing laravel app storage permissions
  file:
    path: "{{ app_path }}/storage/logs"
    mode: 0766
    state: directory

- name: Install composer vendor packages
  composer:
    command: install
    working_dir: "{{ app_path }}"
  become: true
  become_user: "{{ web_user }}"

- name: Creating .env file
  template:
    src: DOTenv.j2
    dest: "{{ app_path }}/.env"
  become: true
  become_user: "{{ web_user }}"