---
# Build playbook should only be run on a new set of servers.
# Be sure to already prepare the required servers beforehand.
# Vagrant: vagrant provision --provision-with main
# VM: ansible-playbook build.yml

- name: Build webserver
  hosts: webservers
  become: true
  become_method: sudo
  roles:
  - basic-rpm
  - webserver

- name: Build dbserver
  hosts: dbservers
  become: true
  become_method: sudo
  roles:
  - basic-rpm
  - dbserver

- name: Build memcached server
  hosts: memcachedservers
  become: true
  become_method: sudo
  roles:
  - basic-rpm
  - memcached

- name: Build redis server
  hosts: redisservers
  become: true
  become_method: sudo
  roles:
  - basic-rpm
  - redis

- name: Build elasticsearch server
  hosts: elasticsearchservers
  become: true
  become_method: sudo
  roles:
  - basic-rpm
  - elasticsearch

- name: Build supervisord server
  hosts: supervisordservers
  become: true
  become_method: sudo
  roles:
  - basic-rpm
  - supervisord

- name: Install guest additions for Vagrant
  hosts: webservers
  become: true
  become_method: sudo
  roles:
    - vagrant-guest-additions