---
- include: build-webserver.yml
- include: build-memcachedserver.yml
- include: build-redisserver.yml
- include: build-dbserver.yml
- include: build-elasticsearchserver.yml
- include: build-supervisord.yml