---
- name: Prepare database
  hosts: dbservers
  become: true
  become_method: sudo
  tasks:
  - include: roles/dbserver/tasks/deploy.yml

- name: Deploy app to webservers
  hosts: webservers
  become: true
  become_method: sudo
  roles:
  - app

- name: Deploy to first webserver
  hosts: webservers[0]
  become: true
  become_method: sudo
  tasks:
  - include: roles/app/tasks/migrate.yml
  - include: roles/app/tasks/import-index.yml
  - include: roles/app/tasks/cron.yml

- name: Deploy to supervisordservers
  hosts: supervisordservers
  become: true
  become_method: sudo
  tasks:
  - include: roles/supervisord/tasks/deploy.yml

- name: Deploy to elasticsearch servers
  hosts: elasticsearchservers
  become: true
  become_method: sudo
  tasks:
  - include: roles/elasticsearchserver/tasks/deploy.yml