---
# To run a deployment, use this command, otherwise it will run the build script as well:
# Vagrant: vagrant provision --provision-with deploy
# VM: ansible-playbook deploy.yml

- name: Prepare database
  hosts: dbservers
  become: true
  become_method: sudo
  roles:
  - mosufy.dbserver-deploy

- name: Deploy app to webservers
  hosts: webservers
  become: true
  become_method: sudo
  roles:
  - mosufy.app

- name: Deploy to first webserver
  hosts: webservers[0]
  become: true
  become_method: sudo
  roles:
  - mosufy.app-master

- name: Deploy to supervisordservers
  hosts: supervisordservers
  become: true
  become_method: sudo
  roles:
  - mosufy.supervisord-deploy