---
# To run a deployment, use this command, otherwise it will run the build script as well:
# Vagrant: vagrant provision --provision-with deploy
# VM: ansible-playbook deploy.yml --tags "deploy"

- name: Deploy config to elasticsearch servers
  hosts: elasticsearchservers
  become: true
  become_method: sudo
  roles:
  - elasticsearchserver

- name: Prepare database
  hosts: dbservers
  become: true
  become_method: sudo
  roles:
  - dbserver

- name: Deploy app to webservers
  hosts: webservers
  become: true
  become_method: sudo
  roles:
  - app

- name: Deploy to first webserver
  hosts: webservers[0]
  become: true
  become_method: sudo
  roles:
  - app

- name: Deploy to supervisordservers
  hosts: supervisordservers
  become: true
  become_method: sudo
  tasks:
  - include: roles/supervisord/tasks/deploy.yml