---
- name: Build app on single initializer webserver
  hosts: webserver-init
  become: true
  become_method: sudo
  roles:
  - app-deploy

- name: Deploy to supervisordservers
  hosts: supervisordservers
  become: true
  become_method: sudo
  roles:
  - supervisord-deploy