#
# Install all roles required
#
# To install roles in ansible/roles dir:
#
# $ cd ansible/
# $ ansible-galaxy install -r install_roles.yml -p roles/
#

- src: mosufy.basic-rpm
- src: mosufy.devel-tools
- src: mosufy.webserver
- src: mosufy.dbserver
- src: mosufy.memcached
- src: mosufy.redis
- src: mosufy.elasticsearch
- src: mosufy.supervisord
- src: mosufy.kernel-devel